# Contact @danguetta with any questions

name: Prepare release
on:
  release:
    types:
      - created

jobs:
  PushRelease:
    env:
      PROJECT: CBS_BA_addin
      APP_ID: 7d4c8374-9811-4c29-900a-a72c423b6a9a
      APP_PUBLISHER: Dynamic Analytics LLC
    if: github.event_name == 'release'
    runs-on: windows-2022
    steps:
    - run: echo "Starting"
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Replace placeholders in installer.iss
      shell: bash
      run: |
        sed -i "s/name_placeholder/${{ env.PROJECT }}/" .github/installer.iss
        sed -i "s/appid_placeholder/${{ env.APP_ID }}/" .github/installer.iss
        sed -i "s/publisher_placeholder/${{ env.APP_PUBLISHER }}/" .github/installer.iss
    - name: Set release version string in installer.iss
      shell: bash
      run: sed -i "s/dev/${{ github.event.release.tag_name }}/" .github/installer.iss
    - name: Create Installer
      run: iscc .github/installer.iss
    - name: Install the sign tool
      shell: bash
      run: dotnet tool install --global AzureSignTool 
    - name: Sign the installer
      shell: bash
      run: AzureSignTool sign -kvu "${{ secrets.AZURE_KEY_VAULT_URI }}" -kvi "${{ secrets.AZURE_CLIENT_ID }}" -kvt "${{ secrets.AZURE_TENANT_ID }}" -kvs "${{ secrets.AZURE_CLIENT_SECRET }}" -kvc ${{ secrets.AZURE_CERT_NAME }} -tr http://timestamp.digicert.com -v .github/Output/${{ env.PROJECT }}.exe
    - name: Upload xlam to the GitHub release
      uses: softprops/action-gh-release@v1
      with:
        files: "CBS_BA_Multiplatform_add_in.xlam"
    - name: Upload use manual to the GitHub release
      uses: softprops/action-gh-release@v1
      with:
        files: "User manual/BA_Add_In_User_Manual.pdf"
    - name: Upload Windows installer to GitHub release
      uses: softprops/action-gh-release@v1
      with:
        files: .github/Output/${{ env.PROJECT }}.exe